backends:
  docker:
    systems:
    - ubuntu-26.04-arm64:
        password: ubuntu
        address: 172.17.0.3
    - ubuntu-26.04-arm64:
        password: ubuntu
        address: 172.17.0.4
    - ubuntu-26.04-arm64:
        password: ubuntu
        address: 172.17.0.5
    - ubuntu-26.04-amd64:
        password: ubuntu
        address: 172.17.0.6
    - ubuntu-26.04-arm64:
        password: ubuntu
        address: 172.17.0.7
    - ubuntu-26.04-amd64:
        password: ubuntu
        address: 172.17.0.8
    - ubuntu-26.04-amd64:
        password: ubuntu
        address: 172.17.0.9
    - ubuntu-26.04-amd64:
        password: ubuntu
        address: 172.17.0.10
