#!/bin/bash
#
# coverage-to-md - Convert coverage report JSON to Markdown format
#
# Usage:
#   coverage-to-md [options] <arguments>
#
# Mandatory arguments to long options are mandatory for short options too.
#   -d, --dir=DIR       Directory containing coverage report JSON files
#   -f, --file=FILE     Single coverage report JSON file
#
# Exit codes:
#   0   Success
#   1   General error
#
# Examples:
#   coverage-to-md -d /path/to/coverage/reports
#   coverage-to-md -f /path/to/coverage/report.json

set -euo pipefail

# json_to_md - Convert a single coverage report JSON to Markdown format
#
# Arguments:
#   $1  JSON file path
#
function json_to_md {
    local jq_filter='.tests | to_entries[] | "\(.key) \(.value.coverage) \(.value.missing | length) \(.value.missing | join(" "))"'
    jq -r "$jq_filter" $1 | while read -r pkg coverage count missing; do
    
    echo "<details>"
    
    if [ "$count" -eq 0 ]; then
        echo "<summary><code>${pkg}</code>: ☂️ ${coverage}% (0 missing)</summary>"
    else
        echo "<summary><code>${pkg}</code>: 🌂 ${coverage}% (${count} missing)</summary>"
        
        echo ""
        echo "\`\`\`"
        
        IFS=' ' read -ra items <<< "$missing"
        for item in "${items[@]}"; do
            echo "$item"
        done
        
        echo "\`\`\`"
    fi
    
    echo "</details>"
    echo ""
    
    done
}

# Main function
#
function main {
    echo "### Test Coverage"

    local dir=""
    local file=""

    # Read arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -d|--dir)
                shift
                dir="$1"
                ;;
            -f|--file)
                shift
                file="$1"
                ;;
            *)
                echo "Unknown argument: $1" >&2
                echo "Usage: $0 -d <dir> | -f <file>" >&2
                exit 1
                ;;
        esac
        shift
    done

    # Process directory
    if [[ -n "$dir" ]]; then
        if [[ ! -d "$dir" ]]; then
            echo "Directory not found: $dir" >&2
            exit 1
        fi

        total=0
        count=0

        md_body=""
        for file in "$dir"/*.json; do
            file_total=$(jq -r '.total_coverage' <$file)
            total=$(echo "$total + $file_total" | bc)
            count=$((count + 1))

            arch=$(basename "$file" | sed -E 's/coverage-report_(.*)\.json/\1/')
            
            md_body+="---"$'\n'
            md_body+="#### Arch: ${arch}"$'\n'
            md_body+="$(json_to_md "$file")"$'\n\n'
        done

        # If there are no files, exit early
        if [ $count -eq 0 ]; then
            echo "No JSON files found in directory: $dir" >&2
            exit 1
        fi

        # Create the Markdown output
        average=$(echo "scale=2; $total / $count" | bc)
        echo "Average Total Coverage: ${average}%"
        echo ""
        echo "$md_body"


    # Process single file
    elif [[ -n "$file" ]]; then
        if [[ ! -f "$file" ]]; then
            echo "File not found: $file" >&2
            exit 1
        fi

        total=$(jq -r '.total_coverage' < "$file")
        echo "Total Coverage: ${total}%"
        echo ""
        json_to_md "$file"
    fi
}

main "$@"