package: gsettings-desktop-schemas

essential:
  - gsettings-desktop-schemas_copyright

slices:
  data:
    contents:
      /usr/share/GConf/gsettings/gsettings-desktop-schemas.convert:
      /usr/share/GConf/gsettings/wm-schemas.convert:
      /usr/share/glib-2.0/schemas/10_gsettings-desktop-schemas.gschema.override:
      /usr/share/glib-2.0/schemas/org.gnome.desktop.*.gschema.xml:
      /usr/share/glib-2.0/schemas/org.gnome.desktop.enums.xml:
      /usr/share/glib-2.0/schemas/org.gnome.system.*.gschema.xml:

  copyright:
    contents:
      /usr/share/doc/gsettings-desktop-schemas/copyright:
