package: libfontconfig1

essential:
  - libfontconfig1_copyright

slices:
  libs:
    essential:
      - fontconfig-config_config
      - libc6_libs
      - libexpat1_libs
      - libfreetype6_libs
    contents:
      /usr/lib/*-linux-*/libfontconfig.so.1*:

  copyright:
    contents:
      /usr/share/doc/libfontconfig1/copyright:
