package: python3-iniconfig

essential:
  - python3-iniconfig_copyright

slices:
  libs:
    essential:
      - python3_standard
    contents:
      /usr/lib/python3/dist-packages/iniconfig-*.egg-info/**:
      /usr/lib/python3/dist-packages/iniconfig/**:

  copyright:
    contents:
      /usr/share/doc/python3-iniconfig/copyright:
