#!/usr/bin/env bash
#spellchecker: ignore rootfs bsdutils scriptlive

rootfs="$(install-slices bsdutils_scriptlive)"

chroot "$rootfs" /usr/bin/scriptlive --help | grep -q "Usage:"
chroot "$rootfs" /usr/bin/scriptlive --version | grep -q "scriptlive from"

# test the scriptlive command with the timing and log files generated by the script command
rootfs_script=$(install-slices bsdutils_script bsdutils_scriptlive dash_bins)
mkdir -p "$rootfs_script"/dev && mount --rbind /dev "$rootfs_script"/dev
trap "umount -l $rootfs_script/dev || true" EXIT
mkdir -p "$rootfs_script"/tmp

export SHELL=/usr/bin/sh
echo -e "printf 'hello scriptlive'\nexit" | chroot "$rootfs_script" /usr/bin/script \
    --log-timing /tmp/scriptlive.tm \
    --log-in /tmp/scriptlive.in \
    --log-out /tmp/scriptlive.out | grep -q "hello scriptlive"

chroot "$rootfs_script" /usr/bin/scriptlive \
    --log-timing /tmp/scriptlive.tm \
    --log-in /tmp/scriptlive.in | grep -q "hello scriptlive"
