#!/usr/bin/env bash
#spellchecker: ignore rootfs bsdutils scriptreplay

rootfs="$(install-slices bsdutils_scriptreplay)"

chroot "$rootfs" /usr/bin/scriptreplay --help | grep -q "Usage:"
chroot "$rootfs" /usr/bin/scriptreplay --version | grep -q "scriptreplay from"

# test the scriptreplay command with the timing and log files generated by the script command
rootfs_script=$(install-slices bsdutils_script bsdutils_scriptreplay dash_bins)
mkdir -p "$rootfs_script"/dev && mount --rbind /dev "$rootfs_script"/dev
trap "umount -l $rootfs_script/dev || true" EXIT
mkdir -p "$rootfs_script"/tmp

export SHELL=/usr/bin/sh
echo -e "printf 'hello scriptreplay'\nexit" | chroot "$rootfs_script" /usr/bin/script \
    --log-timing /tmp/script.tm \
    --log-in /tmp/script.in \
    --log-out /tmp/script.log

chroot "$rootfs_script" /usr/bin/scriptreplay \
    --log-timing /tmp/script.tm \
    --log-out /tmp/script.log | grep -q "hello scriptreplay"
