#!/usr/bin/env bash
# spellchecker: ignore rootfs coreutils gnuarch gnub2sum gnubase32 gnubase64 gnubasename gnubasenc gnucat gnuchcon gnuchgrp gnuchmod gnuchown gnuchroot gnucksum gnucomm gnucp gnucsplit gnucut gnudate gnudd gnudf gnudir gnudircolors gnudirname gnudu gnuecho gnuenv gnuexpand gnuexpr gnufactor gnufalse gnufmt gnufold gnugroups gnuhead gnuhostid gnuid gnuinstall gnujoin gnulink gnuln gnulogname gnuls gnumd5sum gnumkdir gnumkfifo gnumknod gnumktemp gnumv gnunice gnunl gnunohup gnunproc gnunumfmt gnuod gnupaste gnupathchk gnupinky gnupr gnuprintenv gnuprintf gnuptx gnupwd gnureadlink gnurealpath gnurm gnurmdir gnuruncon gnuseq gnusha1sum gnusha224sum gnusha256sum gnusha384sum gnusha512sum gnushred gnushuf gnusleep gnusort gnusplit gnustat gnustdbuf gnustty gnusum gnusync gnutac gnutail gnutee gnutest gnutimeout gnutouch gnutr gnutrue gnutruncate gnutsort gnutty gnuuname gnuunexpand gnuuniq gnuunlink gnuusers gnuvdir gnuwc gnuwho gnuwhoami gnuyes

rootfs="$(install-slices gnu-coreutils_bins)"
cmds=(
    gnuarch
    gnub2sum
    gnubase32
    gnubase64
    gnubasename
    gnubasenc
    gnucat
    gnuchcon
    gnuchgrp
    gnuchmod
    gnuchown
    /usr/sbin/gnuchroot
    gnucksum
    gnucomm
    gnucp
    gnucsplit
    gnucut
    gnudate
    gnudd
    gnudf
    gnudir
    gnudircolors
    gnudirname
    gnudu
    gnuecho
    gnuenv
    gnuexpand
    gnuexpr
    gnufactor
    gnufalse
    gnufmt
    gnufold
    gnugroups
    gnuhead
    gnuhostid
    gnuid
    gnuinstall
    gnujoin
    gnulink
    gnuln
    gnulogname
    gnuls
    gnumd5sum
    gnumkdir
    gnumkfifo
    gnumknod
    gnumktemp
    gnumv
    gnunice
    gnunl
    gnunohup
    gnunproc
    gnunumfmt
    gnuod
    gnupaste
    gnupathchk
    gnupinky
    gnupr
    gnuprintenv
    gnuprintf
    gnuptx
    gnupwd
    gnureadlink
    gnurealpath
    gnurm
    gnurmdir
    gnuruncon
    gnuseq
    gnusha1sum
    gnusha224sum
    gnusha256sum
    gnusha384sum
    gnusha512sum
    gnushred
    gnushuf
    gnusleep
    gnusort
    gnusplit
    gnustat
    gnustdbuf
    gnustty
    gnusum
    gnusync
    gnutac
    gnutail
    gnutee
    gnutimeout
    gnutouch
    gnutr
    gnutrue
    gnutruncate
    gnutsort
    gnutty
    gnuuname
    gnuunexpand
    gnuuniq
    gnuunlink
    gnuusers
    gnuvdir
    gnuwc
    gnuwho
    gnuwhoami
    gnuyes
    "gnu["
)
for cmd in "${cmds[@]}"; do
    chroot "$rootfs" "$cmd" --version | grep -q "coreutils"
done
chroot "$rootfs" gnutest -n "coreutils"
