name: "Get list of maintained releases"
description: >
  Goes through the list of release branches in the chisel-releases repository
  and outputs a list of the currently maintained releases.

outputs:
  maintained-releases:
    description: "List of currently maintained releases"
    value: ${{ steps.get-maintained-releases.outputs.maintained-releases }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y distro-info

    # We could rely on the chisel.yaml "maintained" field, but that would
    # require checking out each releases parsing the file.
    # Instead, we can use the distro-info tool, because in the end, what we
    # care about is whether the release is maintained or not, and not its current
    # maintenance status.
    - shell: bash
      id: get-maintained-releases
      env:
        CR_REPO: "https://github.com/canonical/chisel-releases"
      run: |
        set -x

        all_branches="$(git ls-remote --heads $CR_REPO | grep 'ubuntu-' | cut -f 2 | sed 's/refs\/heads\///g')"

        maintained=()
        set +o pipefail
        for branch in $all_branches; do
          echo "Checking maintenance status for '${branch}'"
          
          if { distro-info --supported -f; distro-info --supported-esm -f; distro-info --devel -f; } \
                | sort | uniq | grep -q "$(echo ${branch#ubuntu-})"
            then
              maintained+=( "$branch" )
          fi
        done

        echo "maintained-releases=$(printf '%s\n' "${maintained[@]}" | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT
