#!/bin/bash
#spellchecker: ignore rootfs maintscript debootstrap coreutils debianutils
#spellchecker: ignore diffutils findutils libc sysvinit libpam

# This test installs all essential packages using dpkg, which requires
# support for running maintainer scripts.

# Note 1: This test alone is not enough to validate the sufficiency of the 
# `dpkg_maintscript-support` slice, as some essential packages will be forced to
# re-install from the deb packages. The completeness of the slice should be further
# validated with the spread test of `apt`

# Note 2: This is for testing only and is not a valid real-world use case of dpkg.
# For the distro-related packages, their initial installation should be performed by
# debootstrap when building the base image by design. For add-on packages, their
# installation should be dictated by apt to sort the dependencies. User installing
# a third-party package should take care of the dependencies on their own, and when
# there are broken deps/installations, they should always run `apt install -f` afterwards,
# but running apt is beyond the scope of this test.

rootfs="$(install-slices dpkg_maintscript-support)"

# NOTE: the essential-packages are generated by the the command
#  dpkg-query -W -f='${Package} ${Essential}\n' | grep yes | cut -d ' ' -f 1
# inside an Ubuntu container.
essential_packages=(
  base-files
  base-passwd
  bash
  coreutils
  # the slices ship the gnu implementation; letting apt pick the uutils one
  # repoints rm at a binary dpkg has not unpacked yet
  coreutils-from-gnu
  dash
  debianutils
  diffutils
  dpkg
  findutils
  grep
  gzip
  hostname
  init-system-helpers
  libc-bin
  ncurses-base
  ncurses-bin
  perl-base
  sed
  sysvinit-utils
  tar
  util-linux
)

# The sliced apt fetches the debs from the release under test, not the test host.
apt_root="$(install-slices apt_apt-get)"
mkdir -p "$apt_root/dev" "$apt_root/debs/partial" "$rootfs/debs"
mount --bind /dev "$apt_root/dev"
cp /etc/resolv.conf "$apt_root/etc/resolv.conf"
touch "$apt_root/empty-status"
chroot "$apt_root" apt-get update
chroot "$apt_root" apt-get -o Dir::Cache::archives=/debs -o Debug::NoLocking=1 -o Dir::State::status=/empty-status \
  install --assume-yes --download-only --no-install-recommends "${essential_packages[@]}"
cp "$apt_root"/debs/*.deb "$rootfs/debs/"
umount "$apt_root/dev"

# the first pass is expected to have some errors due to unmet dependencies for, e.g., libpam-modules and util-linux.
chroot "$rootfs" dpkg --unpack --force-depends -R /debs || true
chroot "$rootfs" dpkg --configure -a || true

# the second pass is expected to succeed
chroot "$rootfs" dpkg --unpack --force-depends -R /debs
chroot "$rootfs" dpkg --configure -a

