#!/usr/bin/env bash

if [[ "$1" != "--spread" ]]; then
    FILE_DIR=$(realpath "$(dirname "$0")")
    source "$FILE_DIR"/setup.sh
else
    # We want to run apt-update only in spreads
    apt update
fi

## TESTS 
# spellchecker: ignore rootfs maintscript distro debootstrap libpam

rootfs="$(install-slices dpkg_dpkg)"

mkdir -p "$rootfs/debs"
# Note: The essential_packages.txt file is generated by the the command
#  dpkg-query -W -f='${Package} ${Essential}\n' | grep yes | cut -d ' ' -f 1
# inside an Ubuntu container.

# shellcheck disable=SC2046
apt-get \
  -o Dir::Cache::archives="$rootfs/debs" \
  -o Debug::NoLocking=1 \
  -o Dir::State::status=/dev/null install \
  --assume-yes \
  --download-only \
  --reinstall \
  --no-install-recommends \
  $(cat essential_packages.txt)

# The first pass is expected to have some errors due to unmet dependencies,
# e.g., libpam-modules and util-linux.
chroot "$rootfs" dpkg --unpack --force-depends -R /debs || true
chroot "$rootfs" dpkg --configure -a || true

# The second pass is expected to succeed.
chroot "$rootfs" dpkg --unpack --force-depends -R /debs
chroot "$rootfs" dpkg --configure -a

