#!/bin/bash -ex
# spellchecker: ignore rootfs

# Installs one or more slices into a dynamically created temporary path.
# Usage: install-slices [<slice>...]
# Returns the path of the chiselled rootfs

function main() {
    local slices="$*"
    # add base-files_chisel slice to ensure we generate the manifest
    slices="${slices} base-files_chisel"

    local rootfs="$(mktemp -d)"
    #shellcheck disable=SC2086
    chisel cut --release "$PROJECT_PATH" --root "$rootfs" $slices
    [ -n "$MANIFESTS_EXPORT_DIR" ] && export_manifests "$rootfs" "$MANIFESTS_EXPORT_DIR"

    echo "${rootfs}"
}

function export_manifests() {
    # copy the manifests to a common export directory
    # manifest is at $rootfs/var/lib/chisel/manifest.wall
    # it will be copied to $manifests_export_dir/$test_name/manifestXXXXX.wall where
    # XXXXX is sequence number (starting from 00000)
    # note that install_slices can be called multiple times from the same test
    local rootfs="$1"
    local manifests_export_dir="$2"
    local test_name=$(basename "$PWD")
    test_name=${test_name:-default}
    local export_dir="$manifests_export_dir/$test_name"
    mkdir -p "$export_dir"
    local seq=$(find "$export_dir" -type f -name 'manifest_*.wall' | wc -l)

    local chisel_manifest_path=$(get_chisel_manifest_path || echo "/var/lib/chisel/manifest.wall")
    cp "$rootfs/$chisel_manifest_path" "$export_dir/manifest_$(printf "%05d" "$seq").wall"
}

function get_chisel_manifest_path() {
    # attempt to parse slices/base_files.yaml, find the `chisel` slice and return
    # the path the manifest.wall file inside it
    _fatal() { echo "$*" >&2; return 1; }
    local base_files_yaml="$PROJECT_PATH/slices/base_files.yaml"
    [ -f "$base_files_yaml" ] || _fatal "no base_files.yaml found"
    command -v yq &> /dev/null || _fatal "yq command not found, cannot parse base_files.yaml"
    local manifest_path=$(yq '.slices.chisel.contents[0] | keys[0]' "$base_files_yaml") || _fatal "failed to parse base_files.yaml"
    [ -n "$manifest_path" ] || _fatal "no chisel slice found in base_files.yaml"
    manifest_path="${manifest_path/%\/\*\*/\/manifest.wall}" # convert the trailing /** to /manifest.wall
    echo "$manifest_path"
}

main "$@"
