#!/bin/bash -e
# spellchecker: ignore rootfs

# Installs one or more slices into a dynamically created temporary path.
# Usage: install-slices [<slice>...]
# Returns the path of the chiselled rootfs

function main() {
    local slices="$*"
    # add base-files_chisel slice to ensure we generate the manifest
    slices="${slices} base-files_chisel"

    local rootfs="$(mktemp -d)"
    chisel_cut "$rootfs" "$slices"
    [ -n "$MANIFESTS_EXPORT_DIR" ] && export_manifests "$rootfs" "$MANIFESTS_EXPORT_DIR"

    echo "${rootfs}"
}

function export_manifests() {
    # copy the manifests to a common export directory
    # manifest is at $rootfs/var/lib/chisel/manifest.wall
    # it will be copied to $manifests_export_dir/$test_name/manifestXXXXX.wall where
    # XXXXX is sequence number (starting from 00000)
    # note that install_slices can be called multiple times from the same test
    local rootfs="$1"
    local manifests_export_dir="$2"
    local test_name=$(basename "$PWD")
    test_name=${test_name:-default}
    local export_dir="$manifests_export_dir/$test_name"
    mkdir -p "$export_dir"
    local seq=$(find "$export_dir" -type f -name 'manifest_*.wall' | wc -l)
    cp "$rootfs/var/lib/chisel/manifest.wall" "$export_dir/manifest_$(printf "%05d" "$seq").wall"
}

_PATTERNS_TO_RETRY=(
    # https://github.com/canonical/chisel-releases/issues/765
    "cannot fetch from archive"
    # https://github.com/canonical/chisel-releases/issues/766
    "cannot talk to archive"
    # https://github.com/canonical/chisel-releases/issues/768
    "cannot find archive data"
)

function chisel_cut() {
    # chisel cut with retry logic for known transient errors
    local rootfs="$1"
    local slices="$2"

    local n_retries=3
    local attempt

    local output=$(mktemp)
    for ((attempt=1; attempt<=n_retries; attempt++)); do
        #shellcheck disable=SC2086
        chisel cut \
            --ignore=unstable \
            --ignore=unmaintained \
            --release "$PROJECT_PATH" \
            --root "$rootfs" \
            $slices \
            2>&1 | tee "$output" >&2
        [[ "${PIPESTATUS[0]}" -eq 0 ]] && break

        local matched=""
        for pattern in "${_PATTERNS_TO_RETRY[@]}"; do
            if grep -q "$pattern" "$output"; then
                matched="$pattern"
                break
            fi
        done

        if [ $attempt -lt $n_retries ] && [ -n "$matched" ]; then
            echo "Warning: Error while installing $slices (attempt $attempt/$n_retries). Retrying..." >&2
            continue
        else
            echo "Failed to cut slices. See above for details." >&2
            exit 1
        fi
    done
}

main "$@"
