# This workflow supports jobs which needs the on.pull_request_target event
# instead of the usual on.pull_request event.
name: Pkg coverage
run-name: Pkg coverage for ${{ github.ref }}

on:
  pull_request_target:
    branches:
      - "ubuntu-*"

jobs:
  pkg-deps:
    name: Package dependencies
    uses: rebornplusplus/chisel-releases/.github/workflows/pkg-deps.yaml@main
