name: Installability tests

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/**"
  schedule:
    # Run at 00:00 every day.
    # Ref: https://man7.org/linux/man-pages/man5/crontab.5.html
    - cron: "0 0 * * *"

jobs:
  install-all-slices:
    name: "Install all slices"
    strategy:
      fail-fast: false
      matrix:
        release:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-23.10
          - ubuntu-24.04
    uses: ./.github/workflows/install-slices.yaml
    with:
      install-all: true
      release-branch: ${{ matrix.release }}
