name: Install slices

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/scripts/affected-slices/**"
      - ".github/scripts/install-slices/**"
      - ".github/workflows/install-slices.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/scripts/affected-slices/**"
      - ".github/scripts/install-slices/**"
      - ".github/workflows/install-slices.yaml"
  schedule:
    # Run at 00:00 every day.
    # Ref: https://man7.org/linux/man-pages/man5/crontab.5.html
    - cron: "0 0 * * *"
  workflow_call:

env:
  # Package architectures and chisel-releases branches to test on.
  ARCHES: '["amd64","arm64","armhf","ppc64el","riscv64","s390x"]'
  RELEASES_COMPATIBILITY: |
    [
      {"ref": "ubuntu-20.04", "chisel-versions": ["v1.1.0","v1.2.0"]},
      {"ref": "ubuntu-22.04", "chisel-versions": ["v1.1.0","v1.2.0","main"]},
      {"ref": "ubuntu-24.04", "chisel-versions": ["v1.1.0","v1.2.0","main"]},
      {"ref": "ubuntu-26.04", "chisel-versions": ["v1.4.2","v1.5.0","main"]},
      {"ref": "ubuntu-26.10", "chisel-versions": ["v1.5.0","main"]}
    ]

jobs:
  prepare-install:
    runs-on: ubuntu-latest
    name: "Prepare to install"
    # Don't run unattended in forks
    if: >-
      github.repository_owner == 'canonical'
      || github.event_name == 'pull_request'
    outputs:
      install-all: ${{ steps.set-output.outputs.install_all }}
      matrix: ${{ steps.set-output.outputs.matrix }}
      checkout-main-ref: ${{ steps.set-main-ref.outputs.checkout_main_ref }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set reference to main branch
        id: set-main-ref
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            # For PRs to main, use the updated files.
            # Leaving checkout_main_ref unset will checkout the PR head_ref.
            echo "checkout_main_ref=" >> $GITHUB_OUTPUT
          else
            echo "checkout_main_ref=main" >> $GITHUB_OUTPUT
          fi

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-main-ref.outputs.checkout_main_ref }}
          fetch-depth: 0

      - name: Set output
        id: set-output
        run: |
          set -ex

          ln -s ".github/scripts/install-slices/version-matrix.py" version-matrix

          if [[
            "${{ github.base_ref || github.ref_name }}" == "main" ||
            "${{ github.event_name }}" == "schedule"
          ]]; then
            # When installing all the slices only use the main version of
            # chisel to avoid expensive CI jobs. We are testing that slices can
            # be installed together so using a single version of chisel is
            # enough.
            all_branches="$(git branch --all | grep -E "remotes.*ubuntu-[0-9]{2}\.[0-9]{2}$" | cut -d '/' -f 3)"

            RELEASES="[]"
            for branch in $all_branches; do
              # Only add to RELEASES when ref is equal to $branch from RELEASES_COMPATIBILITY
              # and the entry in RELEASES_COMPATIBILITY contains "main" in "chisel-versions"
              jq_program='[.[] | select(.ref == $ref) | select(.["chisel-versions"] | index("main")) | ."chisel-versions" = ["main"]]'
              ref="$(echo "$RELEASES_COMPATIBILITY" | jq --arg ref "$branch" "$jq_program")"
              RELEASES="$(echo "$RELEASES" | jq --argjson ref "$ref" '. + $ref')"
            done

            echo "install_all=true" >> $GITHUB_OUTPUT
          else
            if [[
              "${{ github.event_name }}" == "create" &&
              "${{ github.ref_name }}" != "main"
            ]]; then
              # This happens when a new branch/tag is created, so we'll want to
              # install all the slices for that release only
              targetref="${{ github.ref_name }}"
              RELEASES="$(echo $RELEASES_COMPATIBILITY | jq --arg ref "$ref" '[.[] | select(.ref == $ref)]')"
              echo "install_all=true" >> $GITHUB_OUTPUT
            else
              # Filter the releases to only the affected branch, then swap the ref
              # such that the correct branch is tested.
              targetref=""
              RELEASES="$(echo $RELEASES_COMPATIBILITY | jq --arg ref "${{ github.base_ref }}" \
                --arg targetref "$targetref" '[.[] | select(.ref == $ref) | .ref = $targetref]')"
            fi

            # If the {{ github.ref_name }} is not in RELEASES_COMPATIBILITY,
            # then we default to using the main branch of chisel.
            if [[ $(echo $RELEASES | jq 'length') -eq 0 ]]
            then
              RELEASES="[{\"ref\": \"${targetref}\", \"chisel-versions\": [\"main\"]}]"
            fi
          fi

          export RELEASES
     
          MATRIX=$(./version-matrix)
          echo "matrix={\"include\": $MATRIX}" >> $GITHUB_OUTPUT

  # The "install" job tests the slices by installing them.
  # It installs **all** slices if:
  #   - chisel.yaml is changed
  #   - github workflows (and related files) are changed
  # Otherwise, it installs the slices of every package with an affected
  # slice, i.e. an added or modified slice, or one which depends, directly
  # or transitively, on an added, modified or removed slice.
  install:
    runs-on: ubuntu-latest
    name: "Install"
    needs: prepare-install
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-install.outputs.matrix) }}
    env:
      install-all: ${{ needs.prepare-install.outputs.install-all }}
      main-branch-ref: ${{ needs.prepare-install.outputs.checkout-main-ref }}
      main-branch-path: files-from-main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.ref }}

      - name: Setup Go environment
        uses: actions/setup-go@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.main-branch-ref }}
          path: ${{ env.main-branch-path }}

      - name: Install dependencies
        env:
          script-dir: "${{ env.main-branch-path }}/.github/scripts/install-slices"
          affected-script-dir: "${{ env.main-branch-path }}/.github/scripts/affected-slices"
        run: |
          set -ex

          # Install chisel
          # NOTE: This does not run the pre-installation scrip for chisel,
          # so `chisel version` always returns "unknown".
          go install "github.com/canonical/chisel/cmd/chisel@${{ matrix.chisel-version }}"

          # Install dependencies of the install_slices and affected_slices scripts
          sudo apt-get -y update
          sudo apt-get install -y $(cat "${{ env.script-dir }}/deb-requirements.txt")
          pip install -r "${{ env.script-dir }}/requirements.txt"
          pip install -r "${{ env.affected-script-dir }}/requirements.txt"

          # Configure the paths of install_slices and affected_slices scripts
          ln -s "${{ env.script-dir }}/install_slices.py" install-slices
          ln -s "${{ env.affected-script-dir }}/affected_slices.py" affected-slices

      - name: Find affected slices
        run: |
          set -ex
          # On a PR merge commit, the first parent is the tip of the base branch.
          ./affected-slices \
            --release ./ \
            --base HEAD^1 \
            --all="${{ env.install-all }}" \
            > affected.json

      # TODO: As we are installing the slices for every (ref, arch), when
      #   installing all slices, we are also checking the existence of every
      #   package for at least one architecture in a particular release.  This
      #   means that we are running the same check for every arch while running it
      #   for just one arch would have been enough. We should revisit this in
      #   future and propose improvements.
      #   See also https://github.com/canonical/chisel-releases/pull/119#discussion_r1494785644
      - name: Install slices
        env:
          WORKERS: 20
        run: |
          set -ex
          mapfile -t files < <(jq -r '.files[]' affected.json)
          if [[ ${#files[@]} -gt 0 ]]; then
            ./install-slices --arch "${{ matrix.arch }}" --release ./ \
              --ensure-existence \
              --ignore-missing \
              --chisel-version "${{ matrix.chisel-version }}" \
              --workers "${WORKERS}" \
              "${files[@]}"
          fi

      - name: Check installation errors
        run: |
          if [ -s error.log ]; then
            echo "Installation errors found:"
            cat error.log
            exit 1
          fi
