name: Install slices

on:
  workflow_call:
    inputs:
      install-all:
        description: "If true, install all slices in slices/"
        type: boolean
        default: false
        required: false

jobs:
  # The "install" job tests the slices by installing them.
  # It installs **all** slices if:
  #   - inputs.install-all is true
  #   - chisel.yaml is changed
  #   - any slice definition files are deleted
  #   - github workflows (and related files) are changed
  # Otherwise, it installs only the slices from **added** and/or
  # **modified** slice definition files.
  # Please note that "change" is defined to encompass additions,
  # modifications and deletions here.
  install:
    runs-on: ubuntu-latest
    name: "Install"
    strategy:
      fail-fast: false
      matrix:
        ARCH: [amd64, arm64, armhf, i386, ppc64el, riscv64, s390x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed paths
        id: changed-paths
        if: ${{ !inputs.install-all }}
        uses: dorny/paths-filter@v3
        with:
          # ref: https://github.com/marketplace/actions/paths-changes-filter
          filters: |
            install-all:
              - 'chisel.yaml'
              - deleted: 'slices/**/*.yaml'
              - '.github/**'
            slices:
              - added|modified: 'slices/**/*.yaml'
          # Space delimited list usable as command-line argument list in
          # Linux shell. If needed, it uses single or double quotes to
          # wrap filename with unsafe characters.
          list-files: shell

      - name: Setup Go environment
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: |
          go install github.com/canonical/chisel/cmd/chisel@latest
          go install github.com/mikefarah/yq/v4@latest
          wget -q https://raw.githubusercontent.com/canonical/chisel-releases/main/.github/scripts/install-slices
          chmod +x install-slices

      - name: Install all slices
        if: |
          inputs.install-all ||
          steps.changed-paths.outputs.install-all == 'true'
        run: |
          set -e
          # we need to enable globstar to use the ** patterns below
          shopt -s globstar
          ./install-slices --arch "${{ matrix.ARCH }}" --release ./ \
            slices/**/*.yaml

      - name: Install slices from changed files
        if: |
          steps.changed-paths.outputs.slices == 'true' &&
          !(
            inputs.install-all ||
            steps.changed-paths.outputs.install-all == 'true'
          )
        run: |
          set -e
          ./install-slices --arch "${{ matrix.ARCH }}" --release ./ \
            ${{ steps.changed-paths.outputs.slices_files }}
